name: deploy-main

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Configure SSH
              run: |
                  mkdir -p ~/.ssh
                  echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa

                  cat >> ~/.ssh/config <<END
                  Host playground-umc-8th
                    HostName $EC2_HOST
                    User $EC2_USER
                    IdentityFile ~/.ssh/id_rsa
                    StrictHostKeyChecking no
                  END
              env:
                  EC2_USER: ubuntu
                  EC2_HOST: ${{ secrets.EC2_HOST }}
                  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

            - name: Sync files and setup server
              run: |
                  ssh ec2-server '
                    set -e

                    sudo mkdir -p /opt/app &&
                    sudo chown ubuntu:ubuntu /opt/app
                  '

                  rsync -az --delete ./ ec2-server:/opt/app/

            - name: Install and restart in one connection
              run: |
                  ssh ec2-server '
                    set -e

                    cd /opt/app
                    npm install

                    sudo tee /etc/systemd/system/app.service > /dev/null <<EOF
                    [Unit]
                    Description=UMC 8th Project
                    After=network.target

                    [Service]
                    User=ubuntu
                    ExecStart=/usr/bin/npm run dev --prefix /opt/app/
                    Restart=always

                    [Install]
                    WantedBy=multi-user.target
                    EOF

                    sudo systemctl daemon-reload
                    sudo systemctl enable app
                    sudo systemctl restart app
                  '
